// Elements data for Kids Study Tracker
// This file contains all 118 elements with their properties

var ELEMENTS = {
  H:{name_zh:"氢",name_pinyin:"qīng",name_en:"Hydrogen",atomic_number:1,atomic_mass:1.008,category:"nonmetal",category_zh:"非金属",group:"I A",period:1,row:1,col:1,state:"gas",state_icon:"☁",
    properties:[{icon:"🪶",text:"最轻"},{icon:"🔥",text:"易燃"},{icon:"🌌",text:"宇宙最多"}],
    daily_uses:[{icon:"🚀",text:"火箭"},{icon:"⚡",text:"能源"}],
    applications:{daily_items:["水 (H₂O)","食物","塑料","天然气"]},
    intro:"氢是宇宙中最轻最丰富的元素。",
    amazing_facts:["太阳每秒燃烧 6 亿吨氢","氢占宇宙质量 75%","氢气球会爆炸"],
    english_fun:"Riddle: I'm the lightest element! What am I? — Hydrogen!",
    quiz:[{q:"太阳能量来自？",options:["燃烧","核聚变","电","风"],answer:1}]},
  He:{name_zh:"氦",name_pinyin:"hài",name_en:"Helium",atomic_number:2,atomic_mass:4.003,category:"noble_gas",category_zh:"稀有气体",group:"0",period:1,row:1,col:18,state:"gas",state_icon:"☁",
    properties:[{icon:"🎈",text:"轻"},{icon:"🗣️",text:"变声"},{icon:"❄️",text:"超冷"}],
    daily_uses:[{icon:"🎈",text:"气球"},{icon:"🔬",text:"冷却"}],
    applications:{daily_items:["派对气球","MRI 冷却","火箭燃料"]},
    intro:"氦是最冷的元素，-269°C 才变液体。",
    amazing_facts:["吸氦气变卡通声","宇宙第二多元素","从不反应"],
    english_fun:"Fun fact: Helium was discovered in the Sun first!",
    quiz:[{q:"氦气让人声音？",options:["低沉","卡通","消失","回声"],answer:1}]},
  Li:{name_zh:"锂",name_pinyin:"lǐ",name_en:"Lithium",atomic_number:3,atomic_mass:6.94,category:"alkali_metal",category_zh:"碱金属",group:"I A",period:2,row:2,col:1,state:"solid",state_icon:"▪",
    properties:[{icon:"🔋",text:"电池"},{icon:"💊",text:"药物"},{icon:"🔥",text:"遇水燃"}],
    daily_uses:[{icon:"📱",text:"手机"},{icon:"",text:"电动车"}],
    applications:{daily_items:["手机电池","电动车","情绪药"]},
    intro:"锂是最轻的金属，用于电池。",
    amazing_facts:["浮在水上","遇水爆炸","宇宙古老元素"],
    english_fun:"Fun fact: Lithium floats on water!",
    quiz:[{q:"锂用于？",options:["手机","电视","冰箱","洗衣机"],answer:0}]},
  Be:{name_zh:"铍",name_pinyin:"pí",name_en:"Beryllium",atomic_number:4,atomic_mass:9.012,category:"alkaline_earth",category_zh:"碱土金属",group:"II A",period:2,row:2,col:2,state:"solid",state_icon:"▪",
    properties:[{icon:"💎",text:"硬"},{icon:"🔍",text:"X 光"},{icon:"✈️",text:"航空"}],
    daily_uses:[{icon:"️",text:"飞机"},{icon:"🔬",text:"科研"}],
    applications:{daily_items:["飞机零件","X 光窗口","卫星"]},
    intro:"是硬而轻的金属。",
    amazing_facts:["比钢硬但轻","X 光能透过","祖母绿含铍"],
    english_fun:"Fun fact: Beryllium is transparent to X-rays!",
    quiz:[{q:"铍有什么特殊能力？",options:["发光","让 X 光透过","浮在水上","变颜色"],answer:1}]},
  B:{name_zh:"硼",name_pinyin:"péng",name_en:"Boron",atomic_number:5,atomic_mass:10.81,category:"metalloid",category_zh:"类金属",group:"III A",period:2,row:2,col:13,state:"solid",state_icon:"▪",
    properties:[{icon:"🧼",text:"清洁"},{icon:"🌱",text:"植物"},{icon:"🔥",text:"阻燃"}],
    daily_uses:[{icon:"🧴",text:"洗涤剂"},{icon:"🌾",text:"肥料"}],
    applications:{daily_items:["洗涤剂","肥料","防火材料"]},
    intro:"硼是植物的「维生素」。",
    amazing_facts:["植物必需","能去污杀菌","能防火"],
    english_fun:"Fun fact: Boron is like a vitamin for plants!",
    quiz:[{q:"硼对植物像什么？",options:["水","维生素","阳光","土壤"],answer:1}]},
  C:{name_zh:"碳",name_pinyin:"tàn",name_en:"Carbon",atomic_number:6,atomic_mass:12.011,category:"nonmetal",category_zh:"非金属",group:"IV A",period:2,row:2,col:14,state:"solid",state_icon:"▪",
    properties:[{icon:"💎",text:"钻石"},{icon:"️",text:"铅笔"},{icon:"",text:"生命"}],
    daily_uses:[{icon:"💎",text:"珠宝"},{icon:"✏️",text:"铅笔"}],
    applications:{daily_items:["钻石","铅笔芯","食物","塑料"]},
    intro:"碳是「百变之王」。",
    amazing_facts:["钻石和铅笔都是碳","碳有 1000 万种化合物","身体 18% 是碳"],
    english_fun:"Riddle: I can be soft as a pencil or hard as a diamond. What am I? — Carbon!",
    quiz:[{q:"钻石和铅笔芯是什么关系？",options:["完全不同","都是碳","都是金属","都是石头"],answer:1}]},
  N:{name_zh:"氮",name_pinyin:"dàn",name_en:"Nitrogen",atomic_number:7,atomic_mass:14.007,category:"nonmetal",category_zh:"非金属",group:"V A",period:2,row:2,col:15,state:"gas",state_icon:"☁",
    properties:[{icon:"️",text:"空气"},{icon:"❄️",text:"液氮"},{icon:"🌱",text:"肥料"}],
    daily_uses:[{icon:"🌾",text:"氮肥"},{icon:"🍦",text:"冰淇淋"}],
    applications:{daily_items:["空气 78%","氮肥","液氮冰淇淋"]},
    intro:"氮气是空气的主要成分。",
    amazing_facts:["空气 78% 是氮气","液氮 -196°C","豆科植物能固氮"],
    english_fun:"Fun fact: Air is 78% nitrogen!",
    quiz:[{q:"空气中氮气占多少？",options:["21%","50%","78%","99%"],answer:2}]},
  O:{name_zh:"氧",name_pinyin:"yǎng",name_en:"Oxygen",atomic_number:8,atomic_mass:15.999,category:"nonmetal",category_zh:"非金属",group:"VI A",period:2,row:2,col:16,state:"gas",state_icon:"☁",
    properties:[{icon:"🔥",text:"助燃"},{icon:"💧",text:"水"},{icon:"🫁",text:"呼吸"}],
    daily_uses:[{icon:"",text:"医疗"},{icon:"",text:"养殖"}],
    applications:{daily_items:["空气 21%","水","食物"]},
    intro:"氧是维持生命的关键元素。",
    amazing_facts:["空气 21% 是氧","25 亿前没氧气","鱼用鳃抓氧气"],
    english_fun:"Riddle: Fish breathe me from water, you breathe me from air. What am I? — Oxygen!",
    quiz:[{q:"地球大气中氧气占多少？",options:["10%","21%","50%","78%"],answer:1}]},
  F:{name_zh:"氟",name_pinyin:"fú",name_en:"Fluorine",atomic_number:9,atomic_mass:18.998,category:"halogen",category_zh:"卤素",group:"VII A",period:2,row:2,col:17,state:"gas",state_icon:"",
    properties:[{icon:"🦷",text:"牙齿"},{icon:"⚡",text:"活泼"},{icon:"☠️",text:"毒"}],
    daily_uses:[{icon:"🪥",text:"牙膏"},{icon:"🚰",text:"饮用水"}],
    applications:{daily_items:["含氟牙膏","饮用水","不粘锅"]},
    intro:"氟是最活泼的元素。",
    amazing_facts:["最活泼元素","防蛀牙","特氟龙含氟"],
    english_fun:"Fun fact: Fluorine is the most reactive element!",
    quiz:[{q:"氟最厉害的特点？",options:["最重","最活泼","最亮","最冷"],answer:1}]},
  Ne:{name_zh:"氖",name_pinyin:"nǎi",name_en:"Neon",atomic_number:10,atomic_mass:20.180,category:"noble_gas",category_zh:"稀有气体",group:"0",period:2,row:2,col:18,state:"gas",state_icon:"☁",
    properties:[{icon:"💡",text:"发光"},{icon:"🌈",text:"彩色"},{icon:"❄️",text:"超冷"}],
    daily_uses:[{icon:"🏮",text:"霓虹灯"},{icon:"📺",text:"电视"}],
    applications:{daily_items:["霓虹灯","老式电视","温度计"]},
    intro:"氖是「灯光大师」。",
    amazing_facts:["名字意思是「新」","发橙红光","空气中很少"],
    english_fun:"Fun fact: 'Neon' comes from Greek meaning 'new'!",
    quiz:[{q:"霓虹灯的红光来自什么气体？",options:["氧气","气","氢气","氮气"],answer:1}]}
};

console.log("Elements loaded:", Object.keys(ELEMENTS).length);
